Update vector icons to be a peer dependency
This prevents
This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: generateIconSetFromCss